// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAZAmVavI6_H0wBQzRpAn_350SiIdDAck',
    appId: '1:458490123543:web:c523fe25d05eb925779352',
    messagingSenderId: '458490123543',
    projectId: 'daraz-clone-7b875',
    authDomain: 'daraz-clone-7b875.firebaseapp.com',
    storageBucket: 'daraz-clone-7b875.appspot.com',
    measurementId: 'G-1QM2PBMZ36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA512YNkYhF3bfhKSuvahVSOqZkoaVJDm8',
    appId: '1:458490123543:android:3d054abb472ac13e779352',
    messagingSenderId: '458490123543',
    projectId: 'daraz-clone-7b875',
    storageBucket: 'daraz-clone-7b875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmcpDTYQgFRrL-S4T1FToO0xqhDC7ydFs',
    appId: '1:458490123543:ios:7d26ea6aa55e460d779352',
    messagingSenderId: '458490123543',
    projectId: 'daraz-clone-7b875',
    storageBucket: 'daraz-clone-7b875.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmcpDTYQgFRrL-S4T1FToO0xqhDC7ydFs',
    appId: '1:458490123543:ios:8063c0e657c00fb5779352',
    messagingSenderId: '458490123543',
    projectId: 'daraz-clone-7b875',
    storageBucket: 'daraz-clone-7b875.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
